# Generated by Django 3.1.2 on 2020-11-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=100000000)),
                ('short_link', models.CharField(max_length=10000)),
            ],
        ),
    ]
